### ISSUE TITLE
[BUG] Reconnect existed session not work

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphScope#881]
**Describe the bug**
Session reconnect with addr seems not work any more. 
https://github.com/alibaba/GraphScope/blob/db3b5e2a499e1c46cfaf411ad91314750b32216e/python/graphscope/client/session.py#L932-L935

**To Reproduce**
1.  helm install to start a helm graphscope cluster
2. use `sess = graphscope.session(addr='xxxx')` to reconnect the existed session.

```
/anaconda3/envs/gs/lib/python3.9/site-packages/graphscope/client/session.py in _connect(self)
    975 
    976         # waiting service ready
--> 977         self._grpc_client = GRPCClient(self._launcher, self._config_params["reconnect"])
    978         self._grpc_client.waiting_service_ready(
    979             timeout_seconds=self._config_params["timeout_seconds"],

~/anaconda3/envs/gs/lib/python3.9/site-packages/graphscope/client/rpc.py in __init__(self, launcher, reconnect)
     99         self._launcher = launcher
    100         self._channel = grpc.insecure_channel(
--> 101             launcher.coordinator_endpoint, options=options
    102         )
    103         self._stub = coordinator_service_pb2_grpc.CoordinatorServiceStub(self._channel)

AttributeError: 'NoneType' object has no attribute 'coordinator_endpoint'
```

**Expected behavior**
reconnect success.

**Environment (please complete the following information):**
 - GraphScope version: [0.7]
 - OS: [e.g. MacOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by acezen** [comment]
the reconnection may be broke. we should add a ci to test the reconnection?

**Comment by sighingnow** [comment]
Caused by https://github.com/alibaba/GraphScope/pull/751
