### ISSUE TITLE
[BUG] Networkx's convert test has been broken

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#1488]
**Describe the bug**

The convert test has been broken for some time and doesn't work with networkx==2.6, due to following kinds of errors

```python
        >>> d = nx.to_dict_of_dicts(G, edge_data=10)
        >>> d
        {0: {1: 10}, 1: {0: 10}}
        """
        dod = {}
        if nodelist is None:
            if edge_data is None:
                for u, nbrdict in G.adjacency():
>                   dod[u] = nbrdict.copy()
E                   AttributeError: 'NeighborDict' object has no attribute 'copy'
```

We have disabled those test cases in #1487, for more details, see also https://github.com/alibaba/GraphScope/runs/6194670296?check_suite_focus=true
