### ISSUE TITLE
[BUG] AttributeError: module 'graphscope' has no attribute 'nx'

### ISSUE THREAD

**Issue by superad** [alibaba/GraphScope#1130]
**Describe the bug**

**To Reproduce**
1、安装好graphscopeK8S集群，执行报错：
  import graphscope
  import graphscope.nx as nx
  graphscope.set_option(show_log=False)  
2、报错信息:

AttributeError: module 'graphscope' has no attribute 'nx'

**Environment (please complete the following information):**
 - Helm中 chart中 appVersion: 0.9.0
 - 

**Additional context**

**Comment by acezen** [comment]
hi, @superad, the bug has been fixed by commit [e3c6c83](https://github.com/alibaba/GraphScope/commit/e3c6c832f6438a841f85db91b94fe09e119b8610), you  can update the graphscope-client to the commit and try again.

**Comment by acezen** [comment]
related pr: https://github.com/alibaba/GraphScope/pull/1123

**Comment by yecol** [comment]
@lidongze0629 could you update the pip as v0.9.1 to fix this?

**Comment by lidongze0629** [comment]
@superad  You can upgrade  the latest version by `pip3 install graphscope-client==0.9.0 --force-reinstall ` and try again

**Comment by superad** [comment]
ok,it's works!

**Comment by sighingnow** [comment]
Just as a note here:

The different behavior between Python 3.6 and Python 3.7 is caused by https://github.com/python/cpython/pull/1264, which is to solve https://github.com/python/cpython/issues/74210.

Indeed, this change has been documented in [the changelog of Python 3.7](https://docs.python.org/3/whatsnew/3.7.html#other-language-changes):

> Circular imports involving absolute imports with binding a submodule to a name are now supported. (Contributed by Serhiy Storchaka in [bpo-30024](https://bugs.python.org/issue?@action=redirect&bpo=30024).)
